---
title: "Data Analysis"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
library(tidyverse)
library(lubridate)
#install.packages("trend") - runs stationary tests
library(trend)
#install.packages("zoo") - replaces missing values in time series
library(zoo)
#install.packages("Kendall") - specific to one stationary test to be performed
library(Kendall)
#install.packages("tseries")
library(tseries)
library(RColorBrewer)
library(viridis)
library(agricolae)
library(ggplot2)


#set theme
mytheme <- theme_classic(base_size = 14) + 
  theme(axis.text = element_text(color = "black"), 
        legend.position = "right", 
        legend.box.background = element_rect(color="black"), legend.background = element_blank(),  
        plot.title=element_text(hjust = 0.5))
#makes font size bigger, puts legend on right, puts box around legend, centers title in middle
theme_set(mytheme) #setting for all subsequent plots
```

```{r processed.data}
Poop_raw <- read.csv("./Data/Raw/FAOSTAT_data_1980_2050.csv", stringsAsFactors = TRUE)

#filter for desired variables
Poop_filtered <- Poop_raw %>% 
  select(Element, Item, Year:Value)

#filter for CH4 data
Poop_CH4 <- Poop_filtered %>% 
  filter(Element == "Emissions (CH4) (Manure management)")  
  
#filter to remove projected data (removed 2030 and 2050 to eliminate empty years for time series) 
CH4_time <- Poop_CH4 %>% 
  filter(Year %in% c(1980:2018))

#separate items into individual columns
CH4_items <- pivot_wider(CH4_time, names_from=Item, values_from=Value)

```



```{r}
#simple visualization of methane emissions from animals 
CH4_plot <- ggplot(CH4_time, aes(x=Year, y=Value, color=Item))+
  geom_line(size=1.1)+
  labs(y="Methane (gigagrams)", title = "Methane Emissions by Animals", col="Animal")
print(CH4_plot)
```

```{r Time.Series.Cattle.Dairy}
#Create time series component for dairy cattle
CH4_cattle_dairy_ts <- ts(CH4_items$`Cattle, dairy`, start=1980, end=2018)

#Run Mann-Kendall test to test for trend
CH4_cattle_dairy_mk <- mk.test(CH4_cattle_dairy_ts)
CH4_cattle_dairy_mk

#Plot time series
plot.ts(CH4_cattle_dairy_ts)

Cattle_dairy_plot <-
ggplot(CH4_items, aes(x = Year, y = `Cattle, dairy`)) +
  geom_line() +
  labs(y="CH4 Emissions (gigagrams)", title="Methane Emissions for Dairy Cattle", x="Year") +
  geom_smooth( method = lm )
print(Cattle_dairy_plot)

```


```{r Time.Series.Swine.Market}
#Create time series component for market swine
CH4_swine_market_ts <- ts(CH4_items$`Swine, market`, start=1980, end=2018)

#Run Mann-Kendall test to test for trend
CH4_swine_market_mk <- mk.test(CH4_swine_market_ts)
CH4_swine_market_mk

#Plot time series
plot.ts(CH4_swine_market_ts)


Swine_market_plot <-
ggplot(CH4_items, aes(x = Year, y = `Swine, market`)) +
  geom_line() +
  labs(y="CH4 Emissions (gigagrams)", title="Methane Emissions for Market Swine", x="Year") +
  geom_smooth( method = lm )
print(Swine_market_plot)
```


```{r, time series for all years!}
#making filtered dataset for averages
Total.CH4.allyears <- CH4_time %>% 
  group_by(Year) %>% 
  summarise(Mean.Methane=mean(Value),
            Sum.Methane=sum(Value))

#view lineplots
CH4.average.plot <- ggplot(data=Total.CH4.allyears,aes(x=Year, y=Sum.Methane))+
  geom_line()+
  geom_smooth(method = lm )+
  labs(y="Total CH4 (gg)", title="Methane Emissions Over Time")+
  scale_y_continuous(limits = c(1200,1500))
CH4.average.plot

#running time series
Total_ts <- ts(Total.CH4.allyears$Sum.Methane, start=1980, end=2018)

#run Mann-Kendall test to test for trend
Total_ts_mk <- mk.test(Total_ts)
Total_ts_mk #low p-value so there is a trend!
```



```{r}
CH4_asses <- CH4_time %>% 
  filter(Item=="Asses")

CH4_asses_ts <- ts(CH4_asses$Value, start=1980, end=2018, frequency=1)
CH4_asses_decomposed <- stl(CH4_asses_ts, s.window = "periodic")

#use a cowplot
#use plot.ts or ts.plot
#pivot wider to separate items
#trend for time series

```

Anova test and stuff
```{r, viewing boxplot of methane by animal}
CH4.boxplot <- ggplot(data = CH4_time, aes(x=Item, y = Value))+
  geom_boxplot()+
  theme(axis.text.x = element_text(angle=45, hjust=1))+
  labs(title="Average Methane Emissions by Animal", x = "Animal", y = "CH4 Emissions (gigagrams)")
CH4.boxplot
```



```{r, anova normality tests}
# Test for normality. 
# Note: the important assumption for GLMs is normality of residuals, 
# not necessarily normality of raw data. See below when we plot the model.
# shapiro.test() performs the Shapiro-Wilk test of the null that data follows a normal distribution

shapiro.test(CH4_time$Value[CH4_time$Item == "Asses"]) #not normal
shapiro.test(CH4_time$Value[CH4_time$Item == "Cattle, dairy"]) #not normal
shapiro.test(CH4_time$Value[CH4_time$Item == "Cattle, non-dairy"]) #not normal
shapiro.test(CH4_time$Value[CH4_time$Item == "Chickens, broilers"]) #not normal
shapiro.test(CH4_time$Value[CH4_time$Item == "Chickens, layers"]) #not normal
shapiro.test(CH4_time$Value[CH4_time$Item == "Goats"]) #not normal
shapiro.test(CH4_time$Value[CH4_time$Item == "Ducks"]) #normally distributed
shapiro.test(CH4_time$Value[CH4_time$Item == "Horses"]) #not normal
shapiro.test(CH4_time$Value[CH4_time$Item == "Mules"]) #not normal
shapiro.test(CH4_time$Value[CH4_time$Item == "Sheep"]) #not normal
shapiro.test(CH4_time$Value[CH4_time$Item == "Swine, breeding"]) #normally dist
shapiro.test(CH4_time$Value[CH4_time$Item == "Swine, market"]) #normally dist
shapiro.test(CH4_time$Value[CH4_time$Item == "Turkeys"]) #not normal
#most of animals are not normally distributed-reject null in all but 3 cases

qqnorm(CH4_time$Value); qqline(CH4_time$Value)
#data does not follow a normal distribution- some points are way higher quantiles

# Test for equal variance
# ANOVA is robust against departures from equal variance.
# bartlett.test() performs Bartlett's test of the null that the variances in each of the groups (samples) are the same.
bartlett.test(CH4_time$Value ~ CH4_time$Item)
#results: reject null i.e. variances are not equal

#not normal but deciding to proceed anyway
```

```{r, anova}
# Format ANOVA as aov
CH4.anova <- aov(data=CH4_time, Value ~ Item)
summary(CH4.anova)
#results: reject null hypothesis i.e. difference between a pair of animals is statistically significant
#but it's not telling us which animals aren't the same

# Format ANOVA as lm
CH4.anova2 <- lm(data=CH4_time, Value ~ Item)
summary(CH4.anova2)
#intercept represents asses here
#wow, this R2 is 99%!

# Checking model fit and assumptions
# ANOVA is not? robust against departures from normality.
plot(CH4.anova2)
```


```{r, anova post-hoc tests}
# Post-hoc test
# TukeyHSD() computes Tukey Honest Significant Differences
TukeyHSD(CH4.anova)
#outputs all of differences for sites-pvalue for multiple comparisons

# Extract groupings for pairwise relationships
CH4.groups <- HSD.test(CH4.anova, "Item", group = TRUE)
CH4.groups
#sheep, goats, ducks, asses, mules are all in same grouping

# Graph the results
CH4.groups.plot <- ggplot(CH4_time, aes(x=Item, y = Value))+
  geom_boxplot() + 
  theme(axis.text.x = element_text(angle=45, hjust=1))+
  stat_summary(geom="text", fun=max, vjust=-0.5, size=3.5,
               label=c("h", "b", "d", "f", "e", "h", "h", "gh", "h", "h", "c", "a", "fg"), col="purple")+
  labs(x="Animal", y = "CH4 Emissions (gigagrams)")
CH4.groups.plot


```

